Repository hakadoriya-actions/paths-filter-alternative, pull requests merged in 2024-06, with the labels that each got.

#1 feat: init
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/release.yml
  .github/workflows/github-actions-paths-ignore-alternative.yml
  .github/workflows/label-checker.yml
  README.md
  action.yml
Labels: feat

#2 fix: Fix action.yml
  .github/workflows/github-actions-paths-ignore-alternative.yml
  action.yml
Labels: fix

#3 fix: Fix action.yml
  .github/workflows/github-actions-paths-ignore-alternative.yml
  README.md
  action.yml
Labels: fix

#4 fix: Fix action.yml
  .github/workflows/github-actions-paths-ignore-alternative.yml
  action.yml
Labels: fix

#5 fix: Fix action.yml
  .github/workflows/auto-assign.yml
  .github/workflows/github-actions-paths-ignore-alternative.yml
  .github/workflows/task-list-checker.yml
  action.yml
Labels: fix

#7 fix: Fix action.yml
  .github/workflows/example.yml
  README.md
  action.yml
Labels: fix

#8 docs: Fix misc
  .github/workflows/example.yml
  README.md
Labels: docs

#10 chore: fix misc in .github/workflows/example.yml
  .github/workflows/example.yml
Labels: chore

#11 fix: Description must be less than 125 characters
  action.yml
Labels: fix

#12 feat: Add paths parameter for skip
  .github/workflows/example.yml
  README.md
  action.yml
Labels: feat
